### ISSUE TITLE
App Shortcut in Quick Settings

### ISSUE THREAD

**Issue by Vinfall** [thatsmanmeet/Clipboard-Cleaner#1]
The app works fine on my phone. It would be better if you could allow adding app shortcut in quick settings (I suppose it's introduced in Android 12, maybe it would still work on older Android versions), so cleaning clipboard can be easier. In case you need some hints, you can check https://github.com/DeweyReed/ClipboardCleaner.

**Comment by Vinfall** [comment]
Thank you for your work! Hmm, for now when using the app shortcut, it would show a toast notification and open the app. Is it possible to just show the notification?

**Comment by thatsmanmeet** [comment]
I will try to implement Toast without opening the app. I thought the activity opening time will be very less that it might be less noticeable  to users. But I will try to find an alternative for this.

**Comment by Vinfall** [comment]
Maybe keep the app in the background or use accessibility service? The issue is cleaning clipboard would switch to this app, I have to manually switch back to the other app I'm using, which is a bit inconvenient.

**Comment by thatsmanmeet** [comment]
Sure I will find a fix soon. Sorry for inconvenience tho.

**Comment by thatsmanmeet** [comment]
Hi @Vinfall , can you try out new update 1.4 and provide me with any suggestions ?

**Comment by Vinfall** [comment]
Sure, thank you for the quick reply! The weird thing is that using app shortcut would still switch to this app. I suppose it could be a OS issue.

Quoted from https://github.com/DeweyReed/ClipboardCleaner/blob/9cc2ca1c7dad57071bb45e2dfaeef6ad8d8e0e09/app/src/main/res/values/strings.xml#L70-L73:

> From Android 10(Q), Non-input-method apps can't get, modify, and listen to the clipboard in the background.

I don't know how, but the app mentioned above works while your app does not. Some info that may help:
- Device: vivo iQOO Z5x (V2131A)
- Android version: 12 (OriginOS, not the 2nd version aka. OriginOS Ocean)
- App version: 1.4 (tried both version on IzzyOnDroid & Google Play)

**Comment by thatsmanmeet** [comment]
Okay please answer some questions, this will help me understand your exact issue. - Maybe I might be misunderstanding something. 

1. What do you mean exactly by switching to this app ? 

2. How is it causing inconvenience to you ?

3. Is it happening with show clipboard shortcut or clean clipboard shortcut or both ? 

4. What behaviour do you exactly expect to happen ? 

(If possible do share some screenshots or a video highlighting your issue).

I am a little busy these days but knowing your exact problem would help me solve this faster or at least provide some explanation to why that might be happening because from my end, the app seems to work almost perfectly to what I expect on version 1.4.

**Comment by Vinfall** [comment]
I hope this video would answer 1,2 and 4. You can easily notice the difference. As for 3, it's the `clean clipboard` shortcut.

https://user-images.githubusercontent.com/91039000/227832326-231b62de-8d92-45c7-acec-16fd080cfbf3.mp4

I appreciate your work and please take your time❤️

**Comment by thatsmanmeet** [comment]
Hi @Vinfall, I am unable to reproduce the issue you're on my devices. You can see the video of one of my devices below.

https://user-images.githubusercontent.com/120583077/228018885-85fd809d-5220-4602-8cc9-346232f9bd65.mp4

Maybe the issue is related to your OS. Don't worry I will try to see if there are some compatibility issues with Vivo devices or not.

**Comment by thatsmanmeet** [comment]
Hi @Vinfall, I am unable to reproduce the issue you're having on my devices. You can see the video of one of my devices below.


https://user-images.githubusercontent.com/120583077/228020168-fd44ab42-5693-4110-a7b7-1ef1295a5c5f.mp4



Maybe the issue is related to your OS. Don't worry I will try to see if there are some compatibility issues with Vivo devices or not.

**Comment by thatsmanmeet** [comment]
> I hope this video would answer 1,2 and 4. You can easily notice the difference. As for 3, it's the `clean clipboard` shortcut.
> 
> https://user-images.githubusercontent.com/91039000/227832326-231b62de-8d92-45c7-acec-16fd080cfbf3.mp4
> 
> I appreciate your work and please take your time❤️ 

Odd, that isn't supposed to happen. Looks like even the buttons aren't displaying properly on your device. Looks like some type of compatibility issue with jetpack compose (Google's latest Android UI library). Also main activity isn't supposed to be launched on clicking a shortcut in the QS panel.

**Comment by Vinfall** [comment]
> Odd, that isn't supposed to happen. Looks like even the buttons aren't displaying properly on your device. Looks like some type of compatibility issue with jetpack compose (Google's latest Android UI library). Also main activity isn't supposed to be launched on clicking a shortcut in the QS panel.

Agreed. It seems like Vivo customizes the QS panel to make it feel like iOS and that breaks compatibility. I'm willing to share logcat/backtrace/whatever if you can instruct me how to filter out the unnecessary info (like certain keywords to grep only the activity of this app?).
